---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinicapi
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinicapi
  template:
    metadata:
      labels:
        app: petclinicapi
    spec:
      containers:	
      - name: petclinicapi-deployment
        image: tntaksreg.azurecr.io/petclinicapi:latest
        ports:
        - containerPort: 9966

---
apiVersion: v1
kind: Service
metadata:
  name: petclinicapi-service
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: petclinicapi
  ports:	
    - protocol: TCP
      port: 80
      targetPort: 9966

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress	
metadata:
  name: petclinicapi-ingress
  namespace: dev
  annotations:	
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: petclinicapi.e46708b92c054086909b.eastus.aksapp.io
    http:
      paths:
      - backend:
          serviceName: petclinicapi-service
          servicePort: 80
        path: /
